
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "baggiponte", email = "57922983+baggiponte@users.noreply.github.com"},
]
dependencies = [
    "pandas>=2.0.3",
    "seaborn>=0.12.2",
    "scikit-learn>=1.3.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
